spring:
  retry:
    maximum:
      attempts: 3

custom:
  kafka:
    listeners:
      listener-1:
        topic: eacloud
        listener-class: ChildCustomMessageListener

kafka:
  listener:
    topics: default

azure:
  storage:
    account-name: default
    account-key: default
    blob-endpoint: https://default.core.windows.net

